language: node_js

node_js:
  - '8.10.0'
  - 10
  - 12

script: npm run test

jobs:
  include:
    - stage: lint
      node_js: lts/*
      script: npm run lint
    - stage: release
      node_js: lts/*
      script: npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release@15 --branch master

stages:
  - name: lint
  - name: test
  - name: release
    if: branch = master
